positive50 = [
"NAME is such a kind-hearted person.",
"I always enjoy spending time with NAME.",
"It's hard not to admire NAME's determination.",
"NAME has a great sense of humor.",
"I've never met someone as intelligent as NAME.",
"Every conversation with NAME is enlightening.",
"I'm grateful to have NAME as a friend.",
"NAME's positivity is infectious.",
"It's a pleasure to work with NAME.",
"I'm inspired by NAME's creativity.",
"NAME is a true leader.",
"I appreciate NAME's honesty.",
"NAME's energy is invigorating.",
"I've learned a lot from NAME.",
"NAME's compassion knows no bounds.",
"It's easy to trust NAME.",
"NAME always brings a smile to my face.",
"I'm lucky to have NAME in my life.",
"I admire NAME's resilience.",
"Every project with NAME is a success.",
"NAME has a unique perspective.",
"I value NAME's friendship.",
"I'm impressed by NAME's skills.",
"NAME is a great team player.",
"NAME's dedication is unmatched.",
"I look up to NAME.",
"NAME's enthusiasm is contagious.",
"I appreciate NAME's support.",
"I enjoy discussing ideas with NAME.",
"NAME is an excellent listener.",
"I'm thankful for NAME's guidance.",
"I respect NAME's opinions.",
"I'm in awe of NAME's talents.",
"NAME's kindness is heartwarming.",
"It's a pleasure to collaborate with NAME.",
"NAME is a true professional.",
"I'm lucky to know NAME.",
"NAME's insight is valuable.",
"I trust NAME completely.",
"NAME's wisdom is impressive.",
"I admire NAME's dedication to their work.",
"NAME is an outstanding individual.",
"I'm grateful for NAME's friendship.",
"NAME is someone you can always count on.",
"I'm inspired by NAME's passion.",
"NAME has a gift for problem-solving.",
"I'm fortunate to have NAME in my life.",
"I respect NAME's integrity.",
"I enjoy spending time with NAME.",
"NAME's work ethic is admirable."
]

negative50 = [
"I find it hard to get along with NAME.",
"NAME always seems to be in a bad mood.",
"I don't see eye to eye with NAME on anything.",
"NAME's sense of humor is off-putting.",
"I'm often frustrated by NAME's lack of understanding.",
"Conversations with NAME can be draining.",
"I sometimes regret having NAME as a friend.",
"It's challenging to work with NAME.",
"I'm uninspired by NAME's lack of creativity.",
"I don't agree with NAME's leadership style.",
"I've caught NAME being dishonest.",
"NAME's energy can be overwhelming.",
"I've had difficulties learning from NAME.",
"I find NAME to be lacking in compassion.",
"It's hard to trust NAME.",
"NAME's constant complaints bring me down.",
"I could do without NAME in my life.",
"I'm frustrated by NAME's lack of resilience.",
"Projects with NAME can be a challenge.",
"I often struggle to understand NAME's perspective.",
"I question the authenticity of NAME's friendship.",
"I'm unimpressed by NAME's skills.",
"NAME doesn't contribute well to teamwork.",
"I question NAME's commitment.",
"I'm disappointed in NAME's actions.",
"I'm not a fan of NAME's attitude.",
"NAME's lack of enthusiasm is noticeable.",
"I wish NAME would provide more support.",
"I find it hard to engage in meaningful discussions with NAME.",
"NAME doesn't seem to listen or understand.",
"I'm frustrated by NAME's lack of guidance.",
"I disagree with NAME's opinions.",
"I don't see anything remarkable in NAME's talents.",
"I haven't felt much kindness from NAME.",
"Collaborating with NAME can be challenging.",
"I'm unimpressed with NAME's professionalism.",
"I've had better friends than NAME.",
"I find little value in NAME's insights.",
"I have doubts about trusting NAME.",
"I'm not impressed with NAME's wisdom.",
"I question NAME's dedication to their work.",
"I'm unimpressed by NAME's character.",
"I don't feel a genuine connection with NAME.",
"I can't always count on NAME.",
"I'm uninspired by NAME's lack of passion.",
"I don't think NAME is a good problem solver.",
"I've had better people in my life than NAME.",
"I question NAME's integrity.",
"I don't enjoy spending time with NAME.",
"I find NAME's work ethic lacking."
]

neutral50 = [
"NAME is a colleague of mine.",
"I've interacted with NAME on a few occasions.",
"I don't have strong feelings either way about NAME.",
"I find NAME to be quite average.",
"I neither like nor dislike NAME.",
"I don't have much to say about NAME.",
"NAME's personality is neither remarkable nor offensive.",
"I haven't formed a strong opinion about NAME.",
"I'm neutral when it comes to NAME.",
"I don't have any particular impression of NAME.",
"I find NAME to be fairly ordinary.",
"I haven't had any significant interactions with NAME.",
"I don't have a strong connection with NAME.",
"I don't really know much about NAME.",
"I have no reason to have strong feelings about NAME.",
"I've had neutral experiences with NAME.",
"I'm neutral on the matter of NAME.",
"I'm neither impressed nor disappointed by NAME.",
"I don't have any strong positive or negative sentiments about NAME.",
"I don't have any strong emotions regarding NAME.",
"I haven't formed any strong judgments about NAME.",
"I haven't had a remarkable experience with NAME.",
"I'm impartial when it comes to NAME.",
"I'm indifferent to NAME.",
"I don't have any particular views on NAME.",
"I haven't found anything remarkable about NAME.",
"I don't have any personal connection with NAME.",
"I don't have any significant opinions about NAME.",
"I don't have strong feelings one way or the other about NAME.",
"I don't have any specific thoughts on NAME.",
"I haven't formed any strong attachments to NAME.",
"I don't have any significant impressions of NAME.",
"I'm not emotionally invested in NAME.",
"I haven't had any memorable experiences with NAME.",
"I'm neutral in my interactions with NAME.",
"I don't have any notable opinions about NAME.",
"I haven't found anything particularly outstanding or disappointing about NAME.",
"I don't have any noteworthy experiences with NAME.",
"I'm fairly impartial when it comes to NAME.",
"I don't have any strong likes or dislikes for NAME.",
"I don't have any remarkable memories involving NAME.",
"I don't feel strongly one way or the other about NAME.",
"I haven't had any significant positive or negative interactions with NAME.",
"I don't have any strong feelings to share about NAME.",
"I don't have any particularly memorable moments with NAME.",
"I don't have any emotional connection with NAME.",
"I'm fairly neutral in my assessment of NAME.",
"I don't have any strong opinions to express about NAME.",
"I don't have any significant attachments to NAME.",
"I'm fairly neutral in my feelings towards NAME."
]